CREATE TABLE books (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       isbn VARCHAR(20) NOT NULL UNIQUE,
                       title VARCHAR(255) NOT NULL,
                       author VARCHAR(255) NOT NULL,
                       genre VARCHAR(255) NOT NULL,
                       publication_year INT NOT NULL,
                       status VARCHAR(50) NOT NULL
);